language: python
python: 3.8

install:
  - curl -sSL https://install.python-poetry.org | python3 -
  - poetry install

script:
  - poetry run pre-commit run --all-files
  - poetry run <pkg_name> --help
